### ISSUE TITLE
Env Configuration specific not working.

### ISSUE THREAD

**Issue by apsylone** [tchoulom/ViewCounterBundle#25]
When using :

```
tchoulom_view_counter:
  view_counter:
    view_strategy: daily_view
  statistics:
    enabled: false
    stats_file_name: stats
    stats_file_extension:
  storage:
    engine: mongodb
  geolocation:
    geolocator_id: App\Services\Geolocator


when@prod:
  tchoulom_view_counter:
    #geolocation:
    #  geolocator_id: App\Services\Geolocator
    statistics:
      enabled: true
```

The prod environnement config isn't working as expected. It is not surcharged.
It is useful for having in development environnement a not enabled stats config.
